print("          WELCOME         ")
print("Fill the necessary details")

a = input("enter name of School : ")
b = input("enter your First name : ")
c = input("enter your Last name : ")
d = input("enter your Class : ")
e = input("enter your Roll no : ")
f = input("enter your Address : ")
g = input("enter your Contact : ")
h = input("enter your E-mail Id : ")

print("-------------------------------")
print(f"~School  ==> {a}")
print(f"~Name    ==> {b} {c}")
print(f"~Class   ==> {d}")
print(f"~Roll no ==> {e}")
print(f"~Address ==> {f}")
print(f"~Contact ==> {g}")
print(f"~E-mail  ==> {h}")
print("-------------------------------")